### ISSUE TITLE
add azure.eventhub.namespace.connectionstring.get pkg

### ISSUE THREAD

**Issue by chrisdostert** [opspec-pkgs/project#60]
## User Story:
As a consumer of opspec
I want an azure.eventhub.namespace.connectionstring.get pkg
In order to get a connection string of my azure eventhub namespace

## Reference:
- https://github.com/opspec-pkgs/azure.eventhub.namespace.create
- https://github.com/opspec-pkgs/azure.servicebus.namespace.connectionstring.get

**Comment by zachpuck** [comment]
completed: https://github.com/opspec-pkgs/azure.eventhub.namespace.connectionstring.get
