### ISSUE TITLE
add azure.functionapp.deployment.credentials.set

### ISSUE THREAD

**Issue by petedv** [opspec-pkgs/project#68]
When the kudu api is used to deploy code to the azure function, a username and password is required.
This op would set/create those.

**Comment by chrisdostert** [comment]
## Reference
https://docs.microsoft.com/en-us/cli/azure/functionapp/deployment/user#set

**Comment by chrisdostert** [comment]
thanks to @luisgarciaalanis : https://github.com/opspec-pkgs/azure.functionapp.deployment.credentials.set/releases/tag/1.0.0
